site_name: ZestAlgo Book
site_url: https://cheung4843.github.io/ZestAlgo/
repo_url: https://github.com/cheung4843/ZestAlgo
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Fundamental: 
    - fundamental/index.md
    - Python:
      - fundamental/python/index.md
      - Say Hello to Python: fundamental/python/say_hello.md
      - Variables and Input: fundamental/python/variable_and_input.md
      - Operators: fundamental/python/operators.md
      - Selection Structures: fundamental/python/selection_structures.md
      - Repetition Structures: fundamental/python/repetition_structures.md
      - Lists: fundamental/python/lists.md
      - Tuples: fundamental/python/tuples.md
      - Sets: fundamental/python/sets.md
      - Dictionaries: fundamental/python/dictionaries.md
      - Functions: fundamental/python/functions.md
      - Classes: fundamental/python/classes.md
    - C++:
      - fundamental/cpp/index.md
      - 0. 環境架設: fundamental/cpp/0/create_env.md
      - 1. Hello World(輸出與輸入): fundamental/cpp/1/hello_world.md
      - 2. 變數、型態與相關運算:
        - fundamental/cpp/2/index.md
        - 2.1 整數型態: fundamental/cpp/2/interger.md
        - 2.2 浮點數（小數）型態: fundamental/cpp/2/floating.md
        - 2.3 字元: fundamental/cpp/2/char.md
        - 2.4 陣列: fundamental/cpp/2/array.md
        - 2.5 字串: fundamental/cpp/2/string.md
        - 2.6 練習: fundamental/cpp/2/practice.md
  - Algorithm:
    - algorithm/index.md
  - Data Structure:
    - data_structure/index.md
  - Useful Packages:
    - useful_packages/index.md
    - Tkinter:
      - useful_packages/tkinter/index.md
  - Blog:
    - blog/index.md

markdown_extensions:
  - toc:
      permalink: "¶"
      baselevel: 1
      separator: "_"
  # MathJax
  - pymdownx.arithmatex:
      generic: true
  # callout
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # code highlight
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github-alt
  features:
    # header above the content
    - header.autohide
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  logo: imgs/Zest.png
  favicon: imgs/Zest.png
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # - primary: custom
  accent: yellow
  primary: orange
      
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
  language: zh-TW
  anyanalytics:
    gtag: null
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s

extra_css:
  - stylesheets/extra.css

# MathJax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - blog:
      blog_toc: true
      post_date_format: full
      archive_name: Archive
      categories_name: Categories
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-authors
  - git-committers:
      # disabled when building, don't care the error that show in your editor
      enabled: !ENV [CI, false]
      repository: cheung4843/ZestAlgo
      branch: main
      
